# Generated by Django 4.0.5 on 2022-06-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('MobileNo', models.CharField(max_length=20)),
                ('TotalAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Unitprice', models.FloatField()),
                ('total', models.FloatField()),
                ('SalesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sales')),
            ],
        ),
    ]
